#:schema node_modules/wrangler/config-schema.json
name = "schwabauerfamily-server"
main = "src/index.ts"
compatibility_date = "2026-04-01"
workers_dev = false

[observability]
enabled = true

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RsvpDO"]

[[durable_objects.bindings]]
name = "RSVP"
class_name = "RsvpDO"
